### ISSUE TITLE
Github Actionsのアクションとして動かせるようにしたい

### ISSUE THREAD

**Issue by Enchan1207** [Enchan1207/gha-googledrive#3]
既存のスクリプトがあるっちゃ[ある](https://github.com/mathisve/gdrive-upload-action)ので正直あまり意味はないんですが、[ADC](https://cloud.google.com/docs/authentication/application-default-credentials)を使ってみたくて

**Comment by Enchan1207** [comment]
さてアクションの定義ファイルを書いたわけですが…

**Comment by Enchan1207** [comment]
これもしかして、**DockerアクションだとADC取得できない**のでは? Node.jsアクションじゃないとダメ説がある

そうなると… JSで書き直し…??

**Comment by Enchan1207** [comment]
せめてTSにしようよ〜

**Comment by Enchan1207** [comment]
書き直してきました

**Comment by Enchan1207** [comment]
(正直このままmergeでもいい気がしてきた)

**Comment by Enchan1207** [comment]
```yml
name: google-auth

on:
  push:

jobs:
  google_api_access:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: "actions/checkout@v3"

      - uses: google-github-actions/auth@v1
        id: google_auth
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          access_token_scopes: https://www.googleapis.com/auth/drive

      - uses: Enchan1207/gha-googledrive@issue/3-configure-github-actions
        with:
          filepath: README.md
          name: README.txt
          parent: ${{ secrets.FOLDER_ID }}
          overwrite: true
```

こんな感じので一応通るけどさあ！
